
services:
  flask-app:
    build: ./flask_app
    container_name: flask-app-chaos
    ports:
      - "5000:5000"
    restart: always  # Auto-restart after chaos kills it

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  pumba:
    image: gaiaadm/pumba:latest
    container_name: pumba
    command: ["--interval", "30s", "kill", "--signal", "SIGKILL", "re2:^flask-app$"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    restart: always

volumes:
  jenkins_home:
